---
title: "fisheryO: Fisheries Overviews for ICES Advice"
author: "Scott Large"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette

vignette: >
  %\VignetteIndexEntry{"fisheryO: Fisheries Overviews for ICES Advice"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Purpose

The purpose of this document is to report how data were aggregate and manipulated to plot the Fisheries Overviews Advisory Products. The following systems will be included:

1.	Baltic Sea Ecoregion
2.	Azores Ecoregion
3.	Oceanic north-east Atlantic Ecoregion
4.	Bay of Biscay and the Iberian Coast Ecoregion
5.	Celtic Seas Ecoregion
6.	Greater North Sea Ecoregion
7.	Faroes Ecoregion
8.	Icelandic Ecoregion
9.	Norwegian Sea and Barents Sea Ecoregions
10.	Greenland Sea Ecoregion

## Data Sources
The main data for the Fisheries Overviews come from several sources: 

* [Catch Statistics](http://ices.dk/marine-data/dataset-collections/Pages/Fish-catch-and-stock-assessment.aspx) that are officially submitted by 20 ICES member countries and are collected and coordinated in collaboration with the Statistical Office of the European Communities (EUROSTAT). Questions about these data can be directed to <A HREF="mailto:anna.osypchuk@ices.dk?subject=EUROSTAT%20Data">anna.osypchuk@ices.dk</A>
    * Historical (1950-2010)
    * Official Nominal Catches (2006-2014) 
* [Effort Data (STECF)](https://stecf.jrc.ec.europa.eu/documents/43805/870977/2014-12_STECF+14-20+-+Evaluation+of+Fishing+Effort+Regimes+-p2_JRC93183.pdf)
* [Stock Assessment Graphs Database](http://ices.dk/marine-data/tools/Pages/stock-assessment-graphs.aspx) are the assessment results used to provide ICES single stock advice. Questions about these data can be directed to <A HREF="mailto:carlos@ices.dk?subject=SAG%20Data">carlos@ices.dk</A>

## Data manipulation
ICES Catch Statistics, STECF Effort Data, and Stock Assessment output are not provided at consistent spatial aggregations and must be manipulated.

